// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl6OoWP1J_gKdmYcwA1FL_b36Kg82RwCI',
    appId: '1:933078773099:web:cbd9194d11bcfbbf98f02e',
    messagingSenderId: '933078773099',
    projectId: 'alcohol-free-83cab',
    authDomain: 'alcohol-free-83cab.firebaseapp.com',
    storageBucket: 'alcohol-free-83cab.appspot.com',
    measurementId: 'G-3EVJBNFZB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsp8BdCWsNtyLyiW3Q1pX1kZYICZuqUL4',
    appId: '1:933078773099:android:11fbab30db5999fc98f02e',
    messagingSenderId: '933078773099',
    projectId: 'alcohol-free-83cab',
    storageBucket: 'alcohol-free-83cab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATnobyjFScLuGzkYzQaREtRvPF7HqThMw',
    appId: '1:933078773099:ios:ebc5cac3d1185f3398f02e',
    messagingSenderId: '933078773099',
    projectId: 'alcohol-free-83cab',
    storageBucket: 'alcohol-free-83cab.appspot.com',
    iosClientId: '933078773099-fvnkfr8f6bksjbcgo7r8nu7igidrha8d.apps.googleusercontent.com',
    iosBundleId: 'com.gdsc.alcoholFree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATnobyjFScLuGzkYzQaREtRvPF7HqThMw',
    appId: '1:933078773099:ios:ebc5cac3d1185f3398f02e',
    messagingSenderId: '933078773099',
    projectId: 'alcohol-free-83cab',
    storageBucket: 'alcohol-free-83cab.appspot.com',
    iosClientId: '933078773099-fvnkfr8f6bksjbcgo7r8nu7igidrha8d.apps.googleusercontent.com',
    iosBundleId: 'com.gdsc.alcoholFree',
  );
}
